#!/bin/bash
onlytotal() {
    grep -c TODO -r . --include='*.tex' |\
    awk -F : '{total += $2} END { print "Total:", total }'
}

verbose() {
    onlytotal
    echo
    grep -c -r TODO '--include=*.tex' |\
    grep -v ':0$' |\
    awk -F: '{print $1 " " $2}' |\
    sort -n -r -k2
}

if [ $# -gt 0 ] ; then
    verbose
else
    onlytotal
fi
